### ISSUE TITLE
☂️ sBTC deposit ready: half-sprint demo 📽️

### ISSUE THREAD

**Issue by aldur** [stacks-network/sbtc#716]
Prepared by @djordon, thank you!

For the next demo, here are a list of features that we're thinking about targeting:

- [x] The signers automatically deploy the smart contracts on boot. We needed to do this manually before. The work for this is captured by https://github.com/stacks-network/sbtc/issues/688.
- [x] The signers do not accept messages from a signer not in the bootstrap signing set. This should be good to go, the code that enabled this is on main; it was done in https://github.com/stacks-network/sbtc/pull/681.
- [x] We confirm the deposit and then later decide to inform Emily about it. We needed to do this at roughly the same time before. This should be good to go, the code that enabled this is on main; it was done in https://github.com/stacks-network/sbtc/pull/679.
- [x] We do a demo using the actual bridge front-end. Bern, I'm not sure where we are at here.
- [x] We go through validation on the stacks side. This should be good to go, this code for this is on main; it was done in https://github.com/stacks-network/sbtc/pull/694.
- [ ] We go through validation of the bitcoin transaction. This requires https://github.com/stacks-network/sbtc/issues/286.
- [x] We do not issue more than one bitcoin transaction sweeping in the funds. This requires https://github.com/stacks-network/sbtc/issues/585 (with https://github.com/stacks-network/sbtc/issues/709) and https://github.com/stacks-network/sbtc/issues/587.
- [ ] We do not attempt to mint more than once. This requires https://github.com/stacks-network/sbtc/issues/559, https://github.com/stacks-network/sbtc/issues/585 (with https://github.com/stacks-network/sbtc/issues/709), and https://github.com/stacks-network/sbtc/issues/543.

Note that all other issues being currently in-progress or in-review (as of October 28) are in scope for the demo. That means that the above checklist is not exhaustive, look for the "half sprint demo" label.

**Comment by djordon** [comment]
Closing this, as we opened https://github.com/stacks-network/sbtc/issues/778 and https://github.com/stacks-network/sbtc/issues/779 for the issues observed leading up to and during the demo.
